// Products action types
export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START"
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const LOAD_PRODUCTS_ERROR = "LOAD_PRODUCTS_ERROR"

export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR"

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"

export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"


// Orders action types
export const LOAD_ORDERS_START = "LOAD_ORDERS_START"
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS"
export const LOAD_ORDERS_ERROR = "LOAD_ORDERS_ERROR"

export const LOAD_ORDERDETAIL_START = "LOAD_ORDERDETAIL_START"
export const LOAD_ORDERDETAIL_SUCCESS = "LOAD_ORDERDETAIL_SUCCESS"
export const LOAD_ORDERDETAIL_ERROR = "LOAD_ORDERDETAIL_ERROR"

export const DELETE_ORDER_START = "DELETE_ORDER_START"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR"


// Customer action types
export const LOAD_CUSTOMERS_START = "LOAD_CUSTOMERS_START"
export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS"
export const LOAD_CUSTOMERS_ERROR = "LOAD_CUSTOMERS_ERROR"


// Reviews action types
export const LOAD_REVIEWS_START = "LOAD_REVIEWS_START"
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS"
export const LOAD_REVIEWS_ERROR = "LOAD_REVIEWS_ERROR"


// Tenants action types
export const LOAD_TENANTS_START = "LOAD_TENANTS_START"
export const LOAD_TENANTS_SUCCESS = "LOAD_TENANTS_SUCCESS"
export const LOAD_TENANTS_ERROR = "LOAD_TENANTS_ERROR"

export const CREATE_TENANTS_START = "CREATE_TENANTS_START"
export const CREATE_TENANTS_SUCCESS = "CREATE_TENANTS_SUCCESS"
export const CREATE_TENANTS_ERROR = "CREATE_TENANTS_ERROR"

export const DELETE_TENANTS_START = "DELETE_TENANTS_START"
export const DELETE_TENANTS_SUCCESS = "DELETE_TENANTS_SUCCESS"
export const DELETE_TENANTS_ERROR = "DELETE_TENANTS_ERROR"

export const UPDATE_TENANTS_START = "UPDATE_TENANTS_START"
export const UPDATE_TENANTS_SUCCESS = "UPDATE_TENANTS_SUCCESS"
export const UPDATE_TENANTS_ERROR = "UPDATE_TENANTS_ERROR"


// Subscription action types
export const LOAD_SUBSCRIPTION_START = "LOAD_SUBSCRIPTION_START"
export const LOAD_SUBSCRIPTION_SUCCESS = "LOAD_SUBSCRIPTION_SUCCESS"
export const LOAD_SUBSCRIPTION_ERROR = "LOAD_SUBSCRIPTION_ERROR"


// Payment action types
export const LOAD_PAYMENT_START = "LOAD_PAYMENT_START"
export const LOAD_PAYMENT_SUCCESS = "LOAD_PAYMENT_SUCCESS"
export const LOAD_PAYMENT_ERROR = "LOAD_PAYMENT_ERROR"


// Login action types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

// Discounts action types
// export const LOAD_DISCOUNTS_START = "LOAD_DISCOUNTS_START"
// export const LOAD_DISCOUNTS_SUCCESS = "LOAD_DISCOUNTS_SUCCESS"
// export const LOAD_DISCOUNTS_ERROR = "LOAD_DISCOUNTS_ERROR"

export const CREATE_DISCOUNTS_START =   "CREATE_DISCOUNTS_START"
export const CREATE_DISCOUNTS_SUCCESS = "CREATE_DISCOUNTS_SUCCESS"
export const CREATE_DISCOUNTS_ERROR =   "CREATE_DISCOUNTS_ERROR"

// export const DELETE_DISCOUNTS_START =   "DELETE_DISCOUNTS_START"
// export const DELETE_DISCOUNTS_SUCCESS = "DELETE_DISCOUNTS_SUCCESS"
// export const DELETE_DISCOUNTS_ERROR =   "DELETE_DISCOUNTS_ERROR"

// export const UPDATE_DISCOUNTS_START =   "UPDATE_DISCOUNTS_START"
// export const UPDATE_DISCOUNTS_SUCCESS = "UPDATE_DISCOUNTS_SUCCESS"
// export const UPDATE_DISCOUNTS_ERROR =   "UPDATE_DISCOUNTS_ERROR"


// Login action types
export const SUPERADMIN_LOGIN_REQUEST = "SUPERADMIN_LOGIN_REQUEST";
export const SUPERADMIN_LOGIN_SUCCESS = "SUPERADMIN_LOGIN_SUCCESS";
export const SUPERADMIN_LOGIN_FAILURE = "SUPERADMIN_LOGIN_FAILURE";
export const SUPERADMIN_LOGOUT = "SUPERADMIN_LOGOUT";
